### ISSUE TITLE
feature: adblock

### ISSUE THREAD

**Issue by Geraldidi** [RosieCode95/YouTube-Music-Desktop#8]
is there any possibility to avoid ads during playback or after extended playback or after long interaction with youtube which stops playback. 

Kind Regards

**Comment by Ahriana** [comment]
hi, sorry for the delay in the reply..

while yes its possible to add an adblock i dont feel like its the right move as YTM is a paid service which does remove the ads, i dont feel like its a moral move in this case.. not to mention i dont want Google chasing me with a pitchfork
